build:
  maxIssues: 0

config:
  validation: true

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 20
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 8

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
    functionPattern: '^([a-z][a-zA-Z0-9]*)|(`.*`)$'

potential-bugs:
  active: true
  IgnoredReturnValue:
    active: false

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  WildcardImport:
    active: true

